spring:
  application:
    name: service-provider-two
  zipkin:
    base-url: http://localhost:9411
    enabled: true
server:
  port: 9003

eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8080/eureka/,http://peer2:8081/eureka/
